name: TVBox JSON
# 触发器
on:
  schedule:
    - cron: 45 0/4 * * * 
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

        
    - name: Clone project
      run: |
        git clone --depth=1 https://gitcode.net/qq_26898231/TVBox
        rm -rf TVBox/.git
        cp -r TVBox/* ${{ github.workspace }}
        rm -rf TVBox
        sed -i 's/gitcode.net\/qq_26898231\/TVBox\/-\/raw\/main/raw.iqiq.io\/mymine\/tv\/main/g' ${{ github.workspace }}/tv.json
    - name: Update files
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'update files'
        add: ${{ github.workspace }}/*
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: TVBox
        path: TVBox/*
