name: clone 

on:
  schedule:
    - cron: 0 5 * * * 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

        
    - name: clone
      run: |
        rm -rf TVBox
        git clone --depth=1 https://gitcode.net/qq_26898231/TVBox
        rm -rf TVBox/.git
        cp -r TVBox/* /home/runner/work/tv/tv  
    - name: Update spider jar
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'update spider jar'
        add: /home/runner/work/tv/tv/*
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: TVBox
        path: TVBox/*
